services:
  api:
    build: .
    volumes: 
      - ./api:/app
    command: flask run --host "0.0.0.0"
    ports: 
      - "5000:5000"
    depends_on:
      - db
  db: 
    image: postgres
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"